# Dependencies
markdown:         redcarpet
highlighter:      true

# Permalinks
permalink:        pretty

# Setup
url:              http://tian.im
title:            tian.im
tagline:          "Today is a gift. That's why it's called the present."
description:

author:
  name:           Tian

resume:
  url:            http://resume.tian.im
  title:          Resume

paginate:         5

plugins:          [jekyll-paginate]
